# ã‚·ã‚§ãƒ«ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®é–“ã«ç©ºè¡Œã‚’è¿½åŠ ã—ã¾ã™
add_newline = true

[character]
success_symbol = '[ğŸ¤”.oO\(](bold)'
error_symbol = '[ğŸ¤”.oO\(](bold red)'

[cmd_duration]
min_time = 500
format = "[$duration](bold yellow)"

[directory]
style = "bold #a1c9fb"

[git_branch]
format = '[\[$branch\]]($style) '
symbol = ""
style = "bold #aaaaaa"

[git_status]
style = "bold #aaaaaa"
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[golang]
format="[Go ($version )]($style)"
style="bold cyan"

[nodejs]
format = "[Node $version](bold green) "

[python]
format='[${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ""
style="yellow bold"
pyenv_version_name = true

[rust]
format = "[Rust $version](red bold) "

[package]
disabled=true

[gcloud]
format = '[$symbol(\($project\))]($style) '
style = "bold yellow"
symbol="GCP "
